lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    # get "/user/:id", UserController, :id
    resources "/users", UserController
    resources "/tasks", TaskController

    get "/assignments", AssignmentController, :index
    get "/assignments/:id", AssignmentController, :show
    get "/assignments/:task_id/new", AssignmentController, :new
    get "/assignments/:id/edit", AssignmentController, :edit
    post "/assignments", AssignmentController, :create
    put "/assignments", AssignmentController, :update
    delete "/assignments/:id", AssignmentController, :delete

    get "/assignments/timeblock/:id", AssignmentController, :delete_timeblock
    get "/assignments/:assignment_id/new_timeblock", AssignmentController, :new_timeblock
    get "/assignments/:id/edit_timeblock", AssignmentController, :edit_timeblock
    post "/assignments/timeblock", AssignmentController, :create_timeblock
    put "/assignments/timeblock", AssignmentController, :update_timeblock
    delete "/assignments/timeblock/:id", AssignmentController, :delete_timeblock
    

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/timeblock", TimeblockController, except: [:new, :edit]
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user!(user_id || -1)
    assign(conn, :current_user, user)
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker/schedule/task.ex
defmodule Tasktracker.Schedule.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.Schedule.Task


  schema "tasks" do
    field :description, :string
    field :title, :string
    belongs_to :owner, Tasktracker.Accounts.User
    many_to_many :users, Tasktracker.Accounts.User, join_through: Tasktracker.Schedule.Assignment

    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:title, :description, :owner_id])
    |> validate_required([:title, :description, :owner_id])
  end
end

lib/tasktracker_web/controllers/task_controller.ex
defmodule TasktrackerWeb.TaskController do
  use TasktrackerWeb, :controller

  alias Tasktracker.Schedule
  alias Tasktracker.Schedule.Task
  alias Tasktracker.Schedule.Assignment

  def index(conn, _params) do
    user_id = get_session(conn, :user_id)
    if user_id do
      tasks = Schedule.list_tasks_by_owner(user_id)
      render(conn, "index.html", tasks: tasks)
    else
      redirect(conn, to: page_path(conn, :index))
    end
    
  end

  def new(conn, _params) do
    user_id = get_session(conn, :user_id)
    if user_id do
      changeset = Schedule.change_task(%Task{})
      render(conn, "new.html", changeset: changeset)
    else
      redirect(conn, to: page_path(conn, :index))
    end
  end

  def create(conn, %{"task" => task_params}) do
    case Schedule.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Schedule.get_task!(id)
    user_id = get_session(conn, :user_id)
    if user_id do
      if user_id == task.owner_id do
        assignments = Schedule.list_assignments_by_task(id)
        render(conn, "show.html", task: task, assignments: assignments, owned: true)  
      end   
      assignment = Schedule.get_assignment_by_task_and_user(task.id, user_id)
      if assignment do
        render(conn, "show.html", task: task, assignments: [assignment], owned: false)
      end
    end
    redirect(conn, to: page_path(conn, :index))
    
  end

  def edit(conn, %{"id" => id}) do
    user_id = get_session(conn, :user_id)
    task = Schedule.get_task!(id)
    if user_id == task.owner_id do
      changeset = Schedule.change_task(task)
      render(conn, "edit.html", task: task, changeset: changeset)
    else
      redirect(conn, to: page_path(conn, :index))
    end 
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Schedule.get_task!(id)

    case Schedule.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Schedule.get_task!(id)
    {:ok, _task} = Schedule.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end
end

lib/tasktracker_web/views/task_view.ex
defmodule TasktrackerWeb.TaskView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/task/edit.html.eex
<h2>Edit Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: task_path(@conn, :show, @task.id) %></span>

lib/tasktracker_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <%= hidden_input f, :owner_id, value: @current_user.id %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/task/index.html.eex
<h2>Owned Tasks</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>

      <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Complete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: task_path(@conn, :new) %></span>

lib/tasktracker_web/templates/task/new.html.eex
<h2>New Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/tasktracker_web/templates/task/show.html.eex
<h2>Task Detail</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>

</ul>
<%= if !Enum.empty?(@assignments) do %>
  <h3>Assignments</h3>
  <table class="table">
    <thead>
      <tr>
        <td>User</td>
        <td>Time Blocks</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
    <%= for assignment <- @assignments do %>
      <tr>
        <td><%= assignment.user.name %></td>
        <td>
          <ul>
          <%= for timeblock <- assignment.timeblocks do %>
            <li>
              <%= timeblock.start |> NaiveDateTime.truncate :second %> ->
              <%= timeblock.end |> NaiveDateTime.truncate :second %>
            </li>
          <% end %>
          </ul>
        </td>
        <%= if @owned do %>
          <td>
            <span><%= link "Unassign", to: assignment_path(@conn, :delete, assignment), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
          </td>
        <% else %>
          <td>
            <span><%= link "Work Now", to: assignment_path(@conn, :show, assignment.id) %></span>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<div class="row">
<%= if @owned do %>
  <div class="col-md-2">
  <%= link "Edit Task", to: task_path(@conn, :edit, @task) %>
  </div>
  <div class="col-md-2">
  <%= link "Assign", to: assignment_path(@conn, :new, @task.id) %>
  </div>
  <div class="col-md-2">
  <span><%= link "Mark Complete", to: task_path(@conn, :delete, @task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
  </div>
<% end %>
<div class="col-md-3">
<span><%= link "Back", to: task_path(@conn, :index) %></span>
</div>
</div>